# Generated by Django 4.1 on 2022-12-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
